# server {
#     listen 8080;
#     server_name localhost;

#     location / {
#         add_header Content-Type text/plain;
#         return 200 "Hello, World!";
#        # return 200 '<html><body><h1>Hello World!</h1></body></html>';
#     }
# }

# server {
# 	listen 443 ssl;
# 	server_name gaducurt.fr;
	
# 	root /var/www/html;
# 	index index.php index.html;

# 	ssl_certificate etc/nginx/ssl/inception.crt;
# 	ssl_certificate_key etc/nginx/ssl/inception.key;
# 	ssl_protocol	TLSv1.2 TLSv1.3;

# 	location /{
# 		try file $uri $uri/ /index.php?$args;
# 	}

# 	location ~/.php$ {
# 		include fastcgi_params;
# 		fastcgi_pass wordpress:9000;
# 		fastcgi_index index.php;
# 		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
# 	}
# }

user www-data;

worker_processes auto;

pid /run/nginx.pid;

error_log /dev/stderr;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.tipes;
	default_type application/octet-stream;
	access_log /dev/stdout;
	sendfile on;
	server {
		listen 443 ssl;
		server_name gaducurt.fr;
		
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/html;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}
		
		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}