# services:
#   nginx:
#     build:
#       contexte: srcs/requirement/nginx
#       volumes:
#         - db_data:/var/www/html

#   wordpress:
#     build:
#       contexte: srcs/requirement/wordpress
#     ports:
#       - "8080:80"
#     environement:
      
#     depends_on:
#       - mariadb:
#         condition: service_healthy
#     restart: unless-stopped
#     volumes:
#       - db_data:/var/www/html


#   mariadb:
#     build:
#       contexte: srcs/requirement/mariadb
#     environement:
#       MARIABD_DATABASE: wordpress
#       MARIABD_USER: wordpress
#       MARIABD_PASSWORD: /run/secrets/mariadb_password
#       MARIABD_ROOT_PASSWORD: /run/secrets/mariadb_root_password
#     secrets:
#       - mariadb_password
#       - mariadb_root_password
#     volumes:
#       - db_data:var/lib/mariadb
#     healthcheck:
#       test: ["CMD", "ping", "-h", "localhost"]
#       interval: 10s
#       timout: 5s
#       retries: 5
#     restart: unless-stopped

# volumes:
#   db_data

# secrets:
#   mariadb_password:
#     file: ../secrets/db_password.txt
#   mariadb_root_password:
#     file: ../secrets/db_root_password.txt


services:
    mariadb:
        container_name: mariadb
        image: mariadb
        build: requirement/mariadb
        env_file: .env
        secrets:
            - db_password
            - db_root_password
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "mariadb-admin ping -h localhost --silent"]
            interval: 5s
            timout: 3s
            retries: 20
            start_period: 10s

    wordpress:
        container_name: wordpress
        images: wordpress
        build: requirement/wordpress
        env_file: .env
        secrets:
            - db_password
            - credentials
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception
        restart: unless-stopped

    nginx:
        container_name: nginx
        images: nginx
        build: requirement/nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception
        restart: unless-stopped

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${LOGIN}/data/mariadb
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${LOGIN}/data/wordpress

networks:
    inception:
        driver: bridge

secrets:
    db_password:
        file: ../secrets/db_data.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    credentials:
        file: ../secrets/credentials.txt